services:
  - type: web
    name: e-commerce-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add your environment variables here:
      # - key: MONGODB_URI
      #   sync: false  # Set this in Render dashboard
      # - key: JWT_SECRET
      #   sync: false  # Set this in Render dashboard
      # - key: FRONTEND_URL
      #   sync: false  # Set this in Render dashboard
    
  - type: web
    name: e-commerce-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://e-commerce-ngqq.onrender.com/api
